<?PHP
$productos = [
  [
    "id" => "1",
    "titulo" => "Rastaman Vibration",
    "genero" => "Reggae",
    "artista" => "Bob Marley & The Wailers",
    "publicacion" => "1976",
    "productor" => "Island Records",
    "canciones" => 11,
    "bajada" => "Rastaman Vibration es el octavo álbum de estudio de Bob Marley & The Wailers lanzado el 30 de abril de 1976 por el binomio Tuff Gong/Island.",
    "portada" => "marley_rastaman_vibration.jpeg",
    "precio" => 30000
  ],
  [
    "id" => "2",
    "titulo" => "Soul Rebels",
    "genero" => "Reggae",
    "artista" => "Bob Marley & The Wailers",
    "publicacion" => "1970",
    "productor" => "Lee Perry",
    "canciones" => 12,
    "bajada" => "Produced by Lee Perry, the Soul Rebels album was first     issued in 1970 and then was reissued by various labels (sometimes with different names and artwork, similar to Soul Revolution Part II and The Best Of The Wailers).
      Most of these tracks were also included on compilations: 400 Years on African Herbsman (1973), and all tracks except My Sympathy on Rasta Revolution (1974), including numerous budget releases.
      The dub version of the album was released as Soul Rebels Dub.",
    "portada" => "marley_soul_rebel.jpeg",
    "precio" => 40000
  ],
  [
    "id" => "3",
    "titulo" => "Kaya",
    "genero" => "Reggae",
    "artista" => "Bob Marley & The Wailers",
    "publicacion" => "1978",
    "productor" => "Tuff Gong/Island",
    "canciones" => 10,
    "bajada" => "Kaya es el décimo álbum de estudio de Bob Marley, lanzado junto a su banda, The Wailers, en 1978. El álbum, lanzado mediante Tuff Gong e Island, consistía en canciones grabadas desde Exodus, de 1977, hasta ese momento El álbum tenía un sonido muy relajante, carente de la agresividad lírica y musical de los Wailers.",
    "portada" => "marley_kaya.jpeg",
    "precio" => 50000
  ],
  [
    "id" => "4",
    "titulo" => "Exodous",
    "genero" => "Reggae",
    "artista" => "Bob Marley & The Wailers",
    "publicacion" => "1977",
    "productor" => "Island Records",
    "canciones" => 12,
    "bajada" => "Rastaman Vibration es el octavo álbum de estudio de Bob Marley & The Wailers lanzado el 30 de abril de 1976 por el binomio Tuff Gong/Island.",
    "portada" => "marley_exodous.jpeg",
    "precio" => 45000
  ],
  [
    "id" => "5",
    "titulo" => "Natty Dread",
    "genero" => "Reggae",
    "artista" => "Bob Marley & The Wailers",
    "publicacion" => "1974",
    "productor" => "Chris Blackwell y The Wailers",
    "canciones" => 10,
    "bajada" => "Natty Dread es el séptimo álbum de Bob Marley & The Wailers lanzado en 1974. Natty Dread fue el primer álbum lanzado con el nombre de Bob Marley & The Wailers y el primero grabado sin Peter Tosh y Bunny Wailer en la banda.",
    "portada" => "marley_natty_dread.jpeg",
    "precio" => 45000
  ],
  [
    "id" => "6",
    "titulo" => "Survival",
    "genero" => "Reggae",
    "artista" => "Bob Marley & The Wailers",
    "publicacion" => "1979",
    "productor" => "Bob Marley & The Wailers y Alex Sadkin",
    "canciones" => 11,
    "bajada" => "Survival es el undécimo álbum de estudio de Bob Marley & The Wailers y fue lanzado el 2 de octubre de 1979 por los sellos discográficos Tuff Gong y Island Records. El sencillo 'Zimbabwe' es un himno dedicado a la más tarde independiente Rodesia.",
    "portada" => "marley_survival.jpeg",
    "precio" => 48000
  ],
  [
    "id" => "7",
    "titulo" => "Burnin'",
    "genero" => "Reggae",
    "artista" => "Bob Marley & The Wailers",
    "publicacion" => "1973",
    "productor" => "Tuff Gong/Island",
    "canciones" => 10,
    "bajada" => "Burnin' es el sexto álbum de estudio de The Wailers, es el último álbum en contar con los miembros fundadores del grupo Peter Tosh y Bunny Wailer, aquí se encontrarían canciones que se convertirían en clásicos de Bob Marley con The Wailers como 'Get Up, Stand Up' y 'I Shot the Sheriff'.",
    "portada" => "marley_burnin.jpeg",
    "precio" => 60000
  ],
  [
    "id" => "8",
    "titulo" => "Uprising",
    "genero" => "Reggae",
    "artista" => "Bob Marley & The Wailers",
    "publicacion" => "1980",
    "productor" => "Island Records",
    "canciones" => 10,
    "bajada" => "Uprising es el duodécimo álbum de estudio de Bob Marley & The Wailers. Se publicó en 1980 y fue el último de Bob Marley en vida, ya que al año siguiente el mítico cantante moriría.",
    "portada" => "marley_uprising.jpg",
    "precio" => 70000
  ],
  [
    "id" => "9",
    "titulo" => "The Wall",
    "genero" => "Rock",
    "artista" => "Pink Floyd",
    "publicacion" => "1979",
    "productor" => "Columbia Records",
    "canciones" => 24,
    "bajada" => "The Wall —en español: El muro— es el undécimo álbum de estudio del grupo musical británica de rock progresivo Pink Floyd y el segundo doble, se lanzó al mercado en noviembre de 1979 en el Reino Unido y en enero de 1980 en Estados Unidos.",
    "portada" => "floyd_wall.png",
    "precio" => 80000
  ],
  [
    "id" => "10",
    "titulo" => "The Dark Side of the Moon",
    "genero" => "Rock",
    "artista" => "Pink Floyd",
    "publicacion" => "1973",
    "productor" => "Harvest Records",
    "canciones" => 10,
    "bajada" => "The Dark Side of the Moon, en español: El lado oscuro de la luna, es un álbum conceptual, el octavo de estudio del grupo musical británico de rock progresivo Pink Floyd. Fue lanzado el 1 de marzo de 1973 en los Estados Unidos y el 24 de marzo del mismo año en el Reino Unido.",
    "portada" => "floyd_dark.png",
    "precio" => 60000
  ],
  [
    "id" => "11",
    "titulo" => "Wish You Were Here",
    "genero" => "Rock",
    "artista" => "Pink Floyd",
    "publicacion" => "1975",
    "productor" => "Columbia Records",
    "canciones" => 5,
    "bajada" => "Wish You Were Here —en español: Ojalá estuvieras aquí— es el noveno álbum de estudio de la banda británica de rock Pink Floyd, lanzado en septiembre de 1975 e inspirado en el material que compusieron durante su gira europea de 1974 y que grabaron en los Abbey Road Studios de Londres.",
    "portada" => "floyd_wish.jpg",
    "precio" => 70000
  ],
  [
    "id" => "12",
    "titulo" => "The Division Bell",
    "genero" => "Rock",
    "artista" => "Pink Floyd",
    "publicacion" => "1994",
    "productor" => "Columbia Records",
    "canciones" => 11,
    "bajada" => "The Division Bell —en español, La campana de la división— es el decimocuarto álbum de estudio de la banda británica de rock progresivo Pink Floyd. En Reino Unido fue lanzado el 28 de marzo de 1994, a través de la compañía EMI Records, y en Estados Unidos una semana más tarde, a través de Columbia Records.",
    "portada" => "floyd_division_bell.jpeg",
    "precio" => 75000
  ],
  [
    "id" => "13",
    "titulo" => "Pulse",
    "genero" => "Rock",
    "artista" => "Pink Floyd",
    "publicacion" => "1995",
    "productor" => "Columbia Records",
    "canciones" => 26,
    "bajada" => "Pulse —estilizado P·U·L·S·E— es el tercer álbum en vivo de la banda británica de rock progresivo Pink Floyd y el cuarto doble.",
    "portada" => "floyd_pulse.jpg",
    "precio" => 80000
  ],
  [
    "id" => "14",
    "titulo" => "Meddle",
    "genero" => "Rock",
    "artista" => "Pink Floyd",
    "publicacion" => "1971",
    "productor" => "Columbia Records",
    "canciones" => 6,
    "bajada" => "Meddle –en español: «Entrometerse»– es el sexto álbum de estudio de la banda británica de rock progresivo Pink Floyd, editado en octubre de 1971. Se grabó en varios estudios de grabación de la zona de Londres, incluyendo los Abbey Road Studios.",
    "portada" => "floyd_meddle.jpeg",
    "precio" => 62000
  ],
  [
    "id" => "15",
    "titulo" => "The Final Cut",
    "genero" => "Rock",
    "artista" => "Pink Floyd",
    "publicacion" => "1983",
    "productor" => "Columbia Records",
    "canciones" => 12,
    "bajada" => "The Final Cut —en español: El corte final— es el duodécimo álbum de estudio de la banda británica de rock progresivo Pink Floyd. Se lanzó al mercado en marzo de 1983 a través de la compañía discográfica Harvest Records en el Reino Unido y en abril del mismo año a través de Columbia Records en Estados Unidos.",
    "portada" => "floyd_final_cut.jpeg",
    "precio" => 55000
  ],
  [
    "id" => "16",
    "titulo" => "Atom Heart Mother",
    "genero" => "Rock",
    "artista" => "Pink Floyd",
    "publicacion" => "1970",
    "productor" => "Harvest Records",
    "canciones" => 5,
    "bajada" => "Atom Heart Mother - en español Madre De Corazón Atómico - es el quinto álbum de estudio del grupo británico Pink Floyd. Fue lanzado el 2 de octubre de 1970. Es un trabajo de transición, ya que el grupo empieza a alejarse del rock psicodélico para entrar en el sinfónico y progresivo.",
    "portada" => "floyd_atom.jpeg",
    "precio" => 50000
  ],
  [
    "id" => "17",
    "titulo" => "The Beatles",
    "genero" => "Rock/Pop",
    "artista" => "The Beatles",
    "publicacion" => "1968",
    "productor" => "Apple Records",
    "canciones" => 28,
    "bajada" => "The Beatles, también conocido coloquialmente como White Album, o el Álbum Blanco en español, es el noveno álbum de estudio de la banda británica de rock The Beatles, lanzado el 22 de noviembre de 1968.",
    "portada" => "beatles_beatles.jpeg",
    "precio" => 90000
  ],
  [
    "id" => "18",
    "titulo" => "Abbey Road",
    "genero" => "Rock/Pop",
    "artista" => "The Beatles",
    "publicacion" => "1969",
    "productor" => "Apple Records",
    "canciones" => 13,
    "bajada" => "Abbey Road es el undécimo álbum de estudio publicado por la banda británica de rock The Beatles, sería lanzado el 26 de septiembre de 1969 en Reino Unido por Apple Records.",
    "portada" => "beatles_abbey_road.webp",
    "precio" => 80000
  ],
  [
    "id" => "19",
    "titulo" => "Revolver",
    "genero" => "Rock/Pop",
    "artista" => "The Beatles",
    "publicacion" => "1966",
    "productor" => "Parlophone",
    "canciones" => 13,
    "bajada" => "Revolver es el séptimo álbum de estudio de la banda británica de rock The Beatles lanzado el 5 de agosto de 1966 por EMI. Fue el último álbum lanzado antes de que la banda decidiera abandonar los escenarios y las giras, a favor de la experimentación en los estudios de grabación y mejoramiento de su estilo.",
    "portada" => "beatles_revolver.jpg",
    "precio" => 70000
  ],
  [
    "id" => "20",
    "titulo" => "Help!",
    "genero" => "Rock/Pop",
    "artista" => "The Beatles",
    "publicacion" => "1965",
    "productor" => "Parlophone",
    "canciones" => 13,
    "bajada" => "
      Help! es el quinto álbum de estudio de la banda británica de rock, The Beatles, al mismo tiempo que banda sonora de su película de mismo título.",
    "portada" => "beatles_help.jpeg",
    "precio" => 90000
  ],
  [
    "id" => "21",
    "titulo" => "Please Please Me",
    "genero" => "Rock/Pop",
    "artista" => "The Beatles",
    "publicacion" => "1963",
    "productor" => "Parlophone",
    "canciones" => 13,
    "bajada" => "Please Please Me es el álbum debut de la banda británica de rock The Beatles, lanzado el 22 de marzo de 1963 en el Reino Unido. Su publicación acompaña el inicio de la Beatlemanía, después del éxito de los sencillos «Please Please Me» y «Love Me Do».",
    "portada" => "beatles_please.jpeg",
    "precio" => 60000
  ],
  [
    "id" => "22",
    "titulo" => "A Hard Day's Night",
    "genero" => "Rock/Pop",
    "artista" => "The Beatles",
    "publicacion" => "1964",
    "productor" => "United Artists Records",
    "canciones" => 11,
    "bajada" => "A Hard Day's Night es el tercer álbum de estudio de la banda británica de rock, The Beatles, publicado el 10 de julio de 1964 por la compañía discográfica Parlophone, con el número de catálogo PMC 1230 y PCS 3058.",
    "portada" => "beatles_hard_day_night.jpg",
    "precio" => 62000
  ],
  [
    "id" => "23",
    "titulo" => "Rubber Soul",
    "genero" => "Rock/Pop",
    "artista" => "The Beatles",
    "publicacion" => "1965",
    "productor" => "EMI Studios",
    "canciones" => 13,
    "bajada" => "Rubber Soul es el sexto álbum de estudio de la banda británica de rock The Beatles, lanzado el 3 de diciembre de 1965. Producido por George Martin, fue grabado en solo cuatro semanas para así poder aprovechar el mercado navideño.",
    "portada" => "beatles_rubber_soul.jpg",
    "precio" => 70000
  ],
  [
    "id" => "24",
    "titulo" => "Let It Be",
    "genero" => "Rock/Pop",
    "artista" => "The Beatles",
    "publicacion" => "1970",
    "productor" => "EMI Catalogue",
    "canciones" => 12,
    "bajada" => "Let It Be es el duodécimo y último álbum de estudio de la banda de rock inglesa The Beatles. Fue lanzado el 8 de mayo de 1970, días después de que se hiciera oficial la salida de Paul McCartney de la banda, y con ella la disolución pública del grupo.​",
    "portada" => "beatles_let_it_be.webp",
    "precio" => 75000
  ],
  [
    "id" => "25",
    "titulo" => "Sticky Fingers",
    "genero" => "Rock",
    "artista" => "The Rolling Stones",
    "publicacion" => "1971",
    "productor" => "Rolling Stones Records",
    "canciones" => 10,
    "bajada" => "Sticky Fingers —en español: Dedos pegajosos— es el noveno álbum de estudio de la banda de rock británica The Rolling Stones, publicado en abril de 1971.",
    "portada" => "stones_sticky_fingers.webp",
    "precio" => 90000
  ],
  [
    "id" => "26",
    "titulo" => "The Rolling Stones",
    "genero" => "Rock",
    "artista" => "The Rolling Stones",
    "publicacion" => "1964",
    "productor" => "Resurfaced Records",
    "canciones" => 18,
    "bajada" => "The Rolling Stones es el álbum de estudio debut de la banda inglesa de rock The Rolling Stones, lanzado por Decca Records en el Reino Unido el 16 de abril de 1964.",
    "portada" => "stones_rolling_stones.jpeg",
    "precio" => 80000
  ],
  [
    "id" => "27",
    "titulo" => "Exile on Main St.",
    "genero" => "Rock",
    "artista" => "The Rolling Stones",
    "publicacion" => "1972",
    "productor" => "Rolling Stones Records",
    "canciones" => 18,
    "bajada" => "Exile on Main St. —en español: Exilio en la calle Principal— es el décimo en el Reino Unido y duodécimo en los Estados Unidos álbum de estudio de la banda de rock británico The Rolling Stones, publicado en el año 1972.",
    "portada" => "stones_exile.jpeg",
    "precio" => 70000
  ],
  [
    "id" => "28",
    "titulo" => "Let It Bleed",
    "genero" => "Rock",
    "artista" => "The Rolling Stones",
    "publicacion" => "1969",
    "productor" => "ABKCO Records",
    "canciones" => 10,
    "bajada" => "
      Let It Bleed —en español: Déjalo sangrar o Deja que sangre— es el octavo álbum de estudio de The Rolling Stones en el Reino Unido y su décimo en los Estados Unidos. Se publicó el 5 de diciembre de 1969, un año después que su predecesor, Beggars Banquet, que había supuesto un éxito de público y crítica. ",
    "portada" => "stones_let_it_bleed.jpeg",
    "precio" => 90000
  ],
  [
    "id" => "29",
    "titulo" => "Aftermath",
    "genero" => "Rock",
    "artista" => "The Rolling Stones",
    "publicacion" => "1965",
    "productor" => "Decca Records",
    "canciones" => 13,
    "bajada" => "Aftermath es un álbum de estudio de la banda inglesa de rock The Rolling Stones. El grupo grabó el álbum en los estudios RCA de California en diciembre de 1965 y marzo de 1966, durante los descansos entre sus giras internacionales.",
    "portada" => "stones_aftermath.jpeg",
    "precio" => 60000
  ],
  [
    "id" => "30",
    "titulo" => "Tattoo You",
    "genero" => "Rock",
    "artista" => "The Rolling Stones",
    "publicacion" => "1981",
    "productor" => "Rolling Stones Records",
    "canciones" => 11,
    "bajada" => "Tattoo You —en español: Tatúate— es el decimosexto en el Reino Unido y decimoctavo en los Estados Unidos álbum de estudio de la banda de rock británico The Rolling Stones, publicado en 1981",
    "portada" => "stones_tattoo_you.jpg",
    "precio" => 62000
  ],
  [
    "id" => "31",
    "titulo" => "Black and Blue",
    "genero" => "Rock",
    "artista" => "The Rolling Stones",
    "publicacion" => "1976",
    "productor" => "Rolling Stones Records",
    "canciones" => 8,
    "bajada" => "Black And Blue —en español: Negro y azul— es un álbum de estudio de la banda de rock británico The Rolling Stones, lanzado el 23 de abril de 1976. Fue la decimotercera publicación de estudio en el Reino Unido y la decimoquinta en los Estados Unidos.",
    "portada" => "stones_black_blue.jpg",
    "precio" => 70000
  ],
  [
    "id" => "32",
    "titulo" => "Beggars Banquet",
    "genero" => "Rock",
    "artista" => "The Rolling Stones",
    "publicacion" => "1968",
    "productor" => "Decca Records",
    "canciones" => 10,
    "bajada" => "
      Beggars Banquet —en español: El banquete de los mendigos— es el séptimo álbum de estudio en el Reino Unido de la banda de rock británica The Rolling Stones y su noveno en los Estados Unidos. Fue lanzado en diciembre de 1968, un año después que Their Satanic Majesties Request.​",
    "portada" => "stones_beggars_banquet.jpeg",
    "precio" => 75000
  ]
];
